import {
    Mic,
    Target,
    FileText,
    Zap,
    Rocket,
    CreditCard,
    AlertTriangle,
    Scale,
    Bell,
    MessageSquare,
    Megaphone,
    Search,
    Home,
    BookOpen,
    Lightbulb,
    Heart,
    ThumbsUp,
    Copy,
    Check,
    X,
    XCircle,
    CheckCircle,
    Menu,
    User,
    LogOut,
    LogIn,
    UserPlus,
    Settings,
    Wrench,
    Wind,
    Sparkles,
    Quote,
    Play,
    Pause,
    RotateCcw,
    ChevronRight,
    ChevronDown,
    Star,
    Trophy,
    Clock,
    Calendar,
    Send,
    Edit,
    Trash2,
    Eye,
    EyeOff,
    Lock,
    Mail,
    ArrowRight,
    ArrowLeft,
    ExternalLink,
    Info,
    HelpCircle,
    Users,
    TrendingUp,
    Award,
    Shield,
    Volume2,
    VolumeX,
    RefreshCw,
    Filter,
    SortAsc,
    MoreVertical,
    AlertCircle,
    Smile,
    Frown,
    Meh,
    Activity,
    BarChart,
    PieChart,
    Folder,
    File,
    Image,
    Video,
    Music,
    Download,
    Upload,
    Share2,
    Link,
    Bookmark,
    Flag,
    MapPin,
    Globe,
    Phone,
    MessageCircle,
    PlusCircle,
    Shuffle,
    Square,
    FileWarning,
    MicOff,
    MoreHorizontal
} from 'lucide-react';


// Icon mapping from emoji to Lucide icons
const iconMap = {
    // Logo & Branding
    '🎤': Mic,
    'mic': Mic,

    // Actions & Navigation
    '🎯': Target,
    'target': Target,
    '📝': FileText,
    'file-text': FileText,
    '💪': Zap,
    'zap': Zap,
    '⚡': Zap,
    'bolt': Zap,
    '🚀': Rocket,
    'rocket': Rocket,

    // Categories
    '💳': CreditCard,
    'credit-card': CreditCard,
    'billing': CreditCard,
    '⚠️': AlertTriangle,
    'alert-triangle': AlertTriangle,
    'safety': AlertTriangle,
    '⚖️': Scale,
    'scale': Scale,
    'unfair-treatment': Scale,
    '🛎️': Bell,
    'bell': Bell,
    'service': Bell,
    '💬': MessageSquare,
    'message-square': MessageSquare,
    'general': MessageSquare,
    '📢': Megaphone,
    'megaphone': Megaphone,
    'misinformation': Megaphone,
    '🚶': Users,
    'users': Users,

    // UI Elements
    '🔍': Search,
    'search': Search,
    '🏠': Home,
    'home': Home,
    '📚': BookOpen,
    'book-open': BookOpen,
    '💡': Lightbulb,
    'lightbulb': Lightbulb,
    '❤️': Heart,
    'heart': Heart,
    '👍': ThumbsUp,
    'thumbs-up': ThumbsUp,
    '📋': Copy,
    'copy': Copy,
    '✅': CheckCircle,
    'check-circle': CheckCircle,
    '✓': Check,
    'check': Check,
    '❌': XCircle,
    'x-circle': XCircle,
    '✕': X,
    'x': X,
    '☰': Menu,
    'menu': Menu,

    // User & Auth
    '👤': User,
    'user': User,
    '🚪': LogOut,
    'log-out': LogOut,
    '🔑': LogIn,
    'log-in': LogIn,
    '✨': Sparkles,
    'sparkles': Sparkles,

    // Tools
    '🛠️': Wrench,
    'wrench': Wrench,
    '🌬️': Wind,
    'wind': Wind,
    '💫': Sparkles,
    '💭': Quote,
    'quote': Quote,
    '▶️': Play,
    'play': Play,
    '⏸️': Pause,
    'pause': Pause,
    '🔄': RotateCcw,
    'rotate-ccw': RotateCcw,

    // Status & Progress
    '⭐': Star,
    'star': Star,
    '🏆': Trophy,
    'trophy': Trophy,
    '🕐': Clock,
    'clock': Clock,
    '📅': Calendar,
    'calendar': Calendar,

    // Misc
    '📤': Send,
    'send': Send,
    '✏️': Edit,
    'edit': Edit,
    '🗑️': Trash2,
    'trash': Trash2,
    '👁️': Eye,
    'eye': Eye,
    '🔒': Lock,
    'lock': Lock,
    '📧': Mail,
    'mail': Mail,
    '→': ArrowRight,
    'arrow-right': ArrowRight,
    'ℹ️': Info,
    'info': Info,
    '❓': HelpCircle,
    'help-circle': HelpCircle,
    '📈': TrendingUp,
    'trending-up': TrendingUp,
    '🏅': Award,
    'award': Award,
    '🛡️': Shield,
    'shield': Shield,
};

// Get icon component by emoji or name
export const getIcon = (key, props = {}) => {
    const IconComponent = iconMap[key];
    if (IconComponent) {
        return <IconComponent {...props} />;
    }
    // Return null if no icon found (fallback)
    return null;
};

// Icon component with defaults
const Icon = ({
    name,
    size = 24,
    color = 'currentColor',
    strokeWidth = 2,
    className = '',
    ...props
}) => {
    const IconComponent = iconMap[name];

    if (!IconComponent) {
        console.warn(`Icon "${name}" not found in IconMap`);
        return null;
    }

    return (
        <IconComponent
            size={size}
            color={color}
            strokeWidth={strokeWidth}
            className={className}
            {...props}
        />
    );
};

// Export individual icons for direct use
export {
    Mic,
    Target,
    FileText,
    Zap,
    Rocket,
    CreditCard,
    AlertTriangle,
    Scale,
    Bell,
    MessageSquare,
    Megaphone,
    Search,
    Home,
    BookOpen,
    Lightbulb,
    Heart,
    ThumbsUp,
    Copy,
    Check,
    X,
    XCircle,
    CheckCircle,
    Menu,
    User,
    LogOut,
    LogIn,
    UserPlus,
    Settings,
    Wrench,
    Wind,
    Sparkles,
    Quote,
    Play,
    Pause,
    RotateCcw,
    ChevronRight,
    ChevronDown,
    Star,
    Trophy,
    Clock,
    Calendar,
    Send,
    Edit,
    Trash2,
    Eye,
    EyeOff,
    Lock,
    Mail,
    ArrowRight,
    ArrowLeft,
    ExternalLink,
    Info,
    HelpCircle,
    Users,
    TrendingUp,
    Award,
    Shield,
    Volume2,
    VolumeX,
    RefreshCw,
    Filter,
    SortAsc,
    MoreVertical,
    AlertCircle,
    Smile,
    Frown,
    Meh,
    Activity,
    PlusCircle,
    MessageCircle,
    Shuffle,
    Square,
    FileWarning,
    MicOff,
    MoreHorizontal
};

export default Icon;
